version: '3.2'

services:
  apollo:
    build: .
    container_name: apollo_server
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /usr/app
    entrypoint: yarn start
  mongo:
    image: mongo:4
    container_name: mongo_database
    ports:
      - "27018:27017" # expose port for connecting via host client
