service: apollo-server

provider:
  name: aws
  stage: ${self:custom.stage}
  region: us-east-1
  runtime: nodejs8.10
  environment:
    NODE_ENV: ${self:custom.nodeEnv.${self:custom.stage}}
    JWT_SECRET: ${ssm:JWT_SECRET, 'secret'}
    MONGODB_URL: ${ssm:MONGODB_URL, 'mongodb://localhost/database'}
    GRAPHQL_ENDPOINT: /${self:custom.stage}/graphql

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  stage: ${opt:stage, 'dev'}
  nodeEnv:
    dev: development
    prod: production
  webpack:
    includeModules: true
  serverless-offline:
    prefix: ${self:custom.stage}
    useSeparateProcess: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/server.playgroundHandler
    events:
      - http:
          path: playground
          method: get
          cors: true
