service: apollo-server

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs8.10
  environment:
    JWT_SECRET: ${ssm:JWT_SECRET}
    MONGODB_URL: ${ssm:MONGODB_URL}
    GRAPHQL_ENDPOINT: /${self:provider.stage}/graphql

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/server.playgroundHandler
    events:
      - http:
          path: playground
          method: get
          cors: true
